version: "3.8"
services:
  reverse_proxy:
    build:
      context: ./reverse_proxy
    ports:
       - "80:80"
    container_name: reverse_proxy
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/local/backend
    container_name: backend
    ports:
       - "8000:8000"
