version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/app:/usr/share/nginx/html
    ports:
       - "80:80"
    container_name: frontend
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/local/backend
    container_name: backend
    ports:
       - "8000:8000"
